# Generated by Django 5.2.12 on 2026-04-08 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=255, unique=True)),
                ('discord_tag', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discord Profile',
                'verbose_name_plural': 'Discord Profiles',
            },
        ),
    ]
